#!/usr/bin/python

# from github.com/MONROE-PROJECT/Utilities/blob/master/monroe-experiments/usr/bin/metadata

import zmq
import sys

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect ("tcp://172.17.0.1:5556")

socket.setsockopt(zmq.SUBSCRIBE, '')

while True:
    string = socket.recv()
    print string
    sys.stdout.flush()
